apiVersion: v1
kind: Service
metadata:
  name: rstudio
  namespace: release
  labels:
    app: rstudio
spec:
  type: NodePort
  ports:
    - port: 8787
      nodePort: 30001
      name: publish-rstudio
  selector:
    app: rstudio
