name: docker build manager and release

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
env:
  DEVEL_TAG: RELEASE_3_15
  RELEASE_TAG: RELEASE_3_14

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push manager
        id: docker_build_manager
        uses: docker/build-push-action@v2
        with:
          file: inst/docker/Dockerfile.manager
          context: ./inst/docker
          push: true
          tags: bioconductor/bioc-redis:manager
      
      - name: Build and push devel worker
        id: docker_build_devel
        uses: docker/build-push-action@v2
        with:
          file: inst/docker/Dockerfile.worker
          context: ./inst/docker
          push: true
          tags: bioconductor/bioc-redis:${{env.DEVEL_TAG}}
          build-args: |
            RELEASE=devel

      - name: Build and push release worker
        id: docker_build_release
        uses: docker/build-push-action@v2
        with:
          file: inst/docker/Dockerfile.worker
          context: ./inst/docker
          push: true
          tags: bioconductor/bioc-redis:${{env.RELEASE_TAG}}
          build-args: |
            RELEASE=${{env.RELEASE_TAG}}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
