name: test-binary-package-install

on:
  workflow_dispatch:
  schedule:
    - cron: '0 19 * * 1,3,5'

jobs:
  test-built-containers:
    strategy:
      matrix:
        container-tag: [devel, RELEASE_3_13]
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:${{ matrix.container-tag }}

    steps:
      - name: test 5 random packages installation on release and devel
        run: |
          biocsoft <- rownames(available.packages(repos = BiocManager::repositories()[["BioCsoft"]]))
          pkgs <- biocsoft[sample(length(biocsoft), 5)]
          AnVIL::install(pkgs)
          require(pkgs)
        shell: Rscript {0}
